name: pda_printer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  charset_converter: ^2.1.1
  cupertino_icons: ^1.0.2
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  flutter:
    sdk: flutter
  image: ^4.0.17
  intl: ^0.18.1
  path_provider: ^1.6.5
  ping_discover_network: ^0.2.0+1
  qr_flutter: ^4.1.0
  wifi: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg